'use client';
import { useState } from 'react';
import { createClient } from '@/lib/supabase/browser';

type Item={id:string; [key:string]:any};
const fields={skills:['name','category','proficiency','sort_order','status'],projects:['title','slug','summary','description','live_url','source_url','featured','sort_order','status'],experiences:['title','company','location','description','start_date','end_date','is_current','sort_order','status'],achievements:['title','issuer','description','achievement_date','url','sort_order','status']} as const;
const defaults:any={skills:{name:'New skill',status:'published',sort_order:999},projects:{title:'New project',slug:`new-project-${Date.now()}`,summary:'Project summary',status:'draft',featured:false,sort_order:999},experiences:{title:'New role',company:'Company',start_date:new Date().toISOString().slice(0,10),is_current:false,status:'draft',sort_order:999},achievements:{title:'New achievement',status:'published',sort_order:999}};

export default function AdminDashboard({role,site,skills,projects,experiences,achievements,messages}:{role:string;site:any;skills:Item[];projects:Item[];experiences:Item[];achievements:Item[];messages:Item[]}){
 const supabase=createClient(); const [settings,setSettings]=useState(site??{}); const [saving,setSaving]=useState(false); const [notice,setNotice]=useState('');
 async function saveSettings(){setSaving(true);setNotice('');const {error}=await supabase.from('site_settings').upsert({...settings,site_key:'default'});setNotice(error?error.message:'Saved.');setSaving(false);}
 async function add(table:string){const {error}=await supabase.from(table).insert(defaults[table]);if(error)setNotice(error.message);else location.reload();}
 async function remove(table:string,id:string){if(!confirm('Delete this item?'))return;const {error}=await supabase.from(table).delete().eq('id',id);if(error)setNotice(error.message);else location.reload();}
 async function update(table:string,item:Item){const {id,...data}=item;const {error}=await supabase.from(table).update(data).eq('id',id);setNotice(error?'Save failed: '+error.message:'Saved.');}
 function collection(title:string,table:string,items:Item[]){return <section className="rounded-2xl border border-line bg-white p-5"><div className="mb-5 flex items-center justify-between"><h2 className="text-lg font-semibold">{title}</h2><button onClick={()=>add(table)} className="rounded-full bg-ink px-4 py-2 text-xs text-white">Add</button></div>{items.length===0&&<p className="text-sm text-muted">Nothing here yet. Add your first item.</p>}<div className="space-y-4">{items.map(item=><div key={item.id} className="rounded-xl border border-line p-4"><div className="grid gap-3 md:grid-cols-2">{(fields as any)[table].map((key:string)=>typeof item[key]==='boolean'?<label key={key} className="flex items-center gap-2 text-xs text-muted"><input type="checkbox" checked={!!item[key]} onChange={e=>item[key]=e.target.checked} />{key}</label>:<label key={key} className="text-xs text-muted">{key}<input value={item[key]??''} onChange={e=>item[key]=e.target.value} className="mt-1 w-full rounded-lg border border-line px-3 py-2 text-sm text-ink" /></label>)}</div><div className="mt-3 flex justify-end gap-2"><button onClick={()=>update(table,item)} className="rounded-lg bg-ink px-4 py-2 text-xs text-white">Save</button><button onClick={()=>remove(table,item.id)} className="rounded-lg border border-line px-4 py-2 text-xs">Delete</button></div></div>)}</div></section>}
 return <main className="min-h-screen bg-paper"><header className="border-b border-line bg-white"><div className="container-page flex items-center justify-between py-5"><div><p className="text-xs uppercase tracking-widest text-muted">Admin</p><h1 className="text-xl font-semibold">Portfolio CMS</h1></div><div className="flex items-center gap-3"><a href="/" className="rounded-full border border-line px-4 py-2 text-sm">View site</a><button onClick={async()=>{await supabase.auth.signOut();location.href='/admin/login'}} className="rounded-full bg-ink px-4 py-2 text-sm text-white">Sign out</button></div></div></header><div className="container-page space-y-6 py-8"><div className="grid gap-4 sm:grid-cols-4">{[['Projects',projects.length],['Skills',skills.length],['Experience',experiences.length],['Messages',messages.length]].map(([k,v])=><div key={k as string} className="rounded-2xl border border-line bg-white p-5"><p className="text-sm text-muted">{k}</p><p className="mt-2 text-3xl font-semibold">{v as number}</p></div>)}</div>{notice&&<div className="rounded-xl border border-line bg-white px-4 py-3 text-sm">{notice}</div>}<section className="rounded-2xl border border-line bg-white p-5"><h2 className="text-lg font-semibold">Site settings</h2><div className="mt-5 grid gap-4 md:grid-cols-2">{['full_name','headline','bio','email','location','avatar_url','resume_url','github_url','linkedin_url','instagram_url','seo_title','seo_description'].map(key=><label key={key} className="text-xs text-muted">{key}<textarea rows={key==='bio'||key.includes('description')?3:1} value={settings[key]??''} onChange={e=>setSettings({...settings,[key]:e.target.value})} className="mt-1 w-full rounded-lg border border-line px-3 py-2 text-sm text-ink" /></label>)}</div><button onClick={saveSettings} disabled={saving} className="mt-5 rounded-xl bg-ink px-5 py-3 text-sm text-white">{saving?'Saving…':'Save settings'}</button></section>{collection('Skills','skills',skills)}{collection('Projects','projects',projects)}{collection('Experience','experiences',experiences)}{collection('Achievements','achievements',achievements)}<section className="rounded-2xl border border-line bg-white p-5"><h2 className="text-lg font-semibold">Recent contact messages</h2><div className="mt-5 space-y-3">{messages.length===0?<p className="text-sm text-muted">No messages yet.</p>:messages.map(m=><article key={m.id} className="rounded-xl border border-line p-4"><div className="flex justify-between gap-4"><div><p className="font-medium">{m.name} · {m.email}</p><p className="mt-1 text-sm">{m.subject||'No subject'}</p></div><span className="text-xs text-muted">{m.status}</span></div><p className="mt-3 text-sm leading-6 text-muted">{m.message}</p></article>)}</div></section><p className="pb-8 text-xs text-muted">Signed in as {role}. Database RLS is the final authorization boundary.</p></div></main>;
}