create index if not exists project_skills_skill_id_idx on public.project_skills(skill_id);
drop policy if exists settings_admin_write on public.site_settings;
create policy settings_editor_insert on public.site_settings for insert to authenticated with check (private.is_admin_or_editor());
create policy settings_editor_update on public.site_settings for update to authenticated using (private.is_admin_or_editor()) with check (private.is_admin_or_editor());
create policy settings_editor_delete on public.site_settings for delete to authenticated using (private.is_admin_or_editor());
drop policy if exists skills_editor_write on public.skills;
create policy skills_editor_insert on public.skills for insert to authenticated with check (private.is_admin_or_editor());
create policy skills_editor_update on public.skills for update to authenticated using (private.is_admin_or_editor()) with check (private.is_admin_or_editor());
create policy skills_editor_delete on public.skills for delete to authenticated using (private.is_admin_or_editor());
drop policy if exists experiences_editor_write on public.experiences;
create policy experiences_editor_insert on public.experiences for insert to authenticated with check (private.is_admin_or_editor());
create policy experiences_editor_update on public.experiences for update to authenticated using (private.is_admin_or_editor()) with check (private.is_admin_or_editor());
create policy experiences_editor_delete on public.experiences for delete to authenticated using (private.is_admin_or_editor());
drop policy if exists projects_editor_write on public.projects;
create policy projects_editor_insert on public.projects for insert to authenticated with check (private.is_admin_or_editor());
create policy projects_editor_update on public.projects for update to authenticated using (private.is_admin_or_editor()) with check (private.is_admin_or_editor());
create policy projects_editor_delete on public.projects for delete to authenticated using (private.is_admin_or_editor());
drop policy if exists project_skills_editor_write on public.project_skills;
create policy project_skills_editor_insert on public.project_skills for insert to authenticated with check (private.is_admin_or_editor());
create policy project_skills_editor_update on public.project_skills for update to authenticated using (private.is_admin_or_editor()) with check (private.is_admin_or_editor());
create policy project_skills_editor_delete on public.project_skills for delete to authenticated using (private.is_admin_or_editor());
drop policy if exists achievements_editor_write on public.achievements;
create policy achievements_editor_insert on public.achievements for insert to authenticated with check (private.is_admin_or_editor());
create policy achievements_editor_update on public.achievements for update to authenticated using (private.is_admin_or_editor()) with check (private.is_admin_or_editor());
create policy achievements_editor_delete on public.achievements for delete to authenticated using (private.is_admin_or_editor());
drop policy if exists profiles_self_read on public.profiles;
create policy profiles_self_read on public.profiles for select to authenticated using ((select auth.uid()) = id or private.is_admin());
drop policy if exists audit_authenticated_insert on public.audit_logs;
create policy audit_authenticated_insert on public.audit_logs for insert to authenticated with check ((select auth.uid()) is not null and actor_id = (select auth.uid()));
grant execute on function private.is_admin() to anon, authenticated;
grant execute on function private.is_admin_or_editor() to anon, authenticated;
revoke execute on function public.rls_auto_enable() from anon, authenticated, public;
